### ISSUE TITLE
I'm getting KeyError: 'PATH'

### ISSUE THREAD

**Issue by Leonime** [ui/django-thumbnails#82]
The only things I did was install django-thumbnails, created a model.

here is the model.
```
from django.db import models
from thumbnails.fields import ImageField


class Food(models.Model):
    image = ImageField()
```
the configuration

```
THUMBNAILS = {
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
    'STORAGE': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        # You can also use Amazon S3 or any other Django storage backends
    },
    'SIZES': {
        'small': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 10, 'height': 10},
                {'PATH': 'thumbnails.processors.crop', 'width': 80, 'height': 80}
            ],
            'POST_PROCESSORS': [
                {
                    'processor': 'thumbnails.post_processors.optimize',
                    'png_command': 'optipng -force -o7 "%(filename)s"',
                    'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
                },
            ],
        },
        'large': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                {'PATH': 'thumbnails.processors.flip', 'direction': 'horizontal'}
            ],
        }
    }
}
```
an then when I run 
```
python manage.py makemigrations
```
I get this error
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/solid/Projects/repos/simple_django/cooking/models.py", line 2, in <module>
    from thumbnails.fields import ImageField
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/thumbnails/fields.py", line 8, in <module>
    from .backends import metadata, storage
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/thumbnails/backends/metadata.py", line 3, in <module>
    from thumbnails import compat, conf
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/thumbnails/conf.py", line 30, in <module>
    SIZES[size]['POST_PROCESSORS'] = parse_processors(SIZES[size]['POST_PROCESSORS'])
  File "/home/leonime/.cache/pypoetry/virtualenvs/simple-django-y5eEogUp-py3.8/lib/python3.8/site-packages/thumbnails/utils.py", line 40, in parse_processors
    processor_function = import_attribute(processor['PATH'])
KeyError: 'PATH'
```

**Comment by Almidi** [comment]
I have the exact same problem.
Any way to solve this ?

**Comment by Almidi** [comment]
Change your configuration from 
`'processor': 'thumbnails.post_processors.optimize' `
to
`'PATH': 'thumbnails.post_processors.optimize',`

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-thumbnails/commit/8cc25f39bd4cfff85f5fcfbdcd9dc78b571a1ec4
