### ISSUE TITLE
Redis is required even metadata uses DatabaseBackend

### ISSUE THREAD

**Issue by kodziek** [ui/django-thumbnails#83]
Even I use `DatabaseBackend` for metadata
```python
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
```
I cannot run any migration after changing `models.ImageField` to `thumbnails.ImageField`

See error below:

```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "...-uOycRjUm/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "...-uOycRjUm/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "...-uOycRjUm/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "...-uOycRjUm/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "...-uOycRjUm/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../pages/models.py", line 7, in <module>
    from galleries.models import Picture
  File ".../galleries/models.py", line 4, in <module>
    from thumbnails.fields import ImageField
  File "...-uOycRjUm/lib/python3.6/site-packages/thumbnails/fields.py", line 8, in <module>
    from .backends import metadata, storage
  File "...-uOycRjUm/lib/python3.6/site-packages/thumbnails/backends/metadata.py", line 1, in <module>
    from redis import StrictRedis
ModuleNotFoundError: No module named 'redis'
```

**Comment by Schwankenson** [comment]
Same here

**Comment by rishthas** [comment]
Same here. Please fix this asap.

**Comment by ppppfly** [comment]
Same issue, and not expect to use Redis.
